//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mayfly.Benthos.Resources.Interface {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Grade {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Grade() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mayfly.Benthos.Resources.Interface.Grade", typeof(Grade).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cacoon.
        /// </summary>
        internal static string Cacoon {
            get {
                return ResourceManager.GetString("Cacoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCN.
        /// </summary>
        internal static string CacoonR {
            get {
                return ResourceManager.GetString("CacoonR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emerger.
        /// </summary>
        internal static string Emerger {
            get {
                return ResourceManager.GetString("Emerger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMG.
        /// </summary>
        internal static string EmergerR {
            get {
                return ResourceManager.GetString("EmergerR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult / Imago.
        /// </summary>
        internal static string Imago {
            get {
                return ResourceManager.GetString("Imago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMG.
        /// </summary>
        internal static string ImagoR {
            get {
                return ResourceManager.GetString("ImagoR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larv / Nymph.
        /// </summary>
        internal static string Larva {
            get {
                return ResourceManager.GetString("Larva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LRV.
        /// </summary>
        internal static string LarvaR {
            get {
                return ResourceManager.GetString("LarvaR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepupa.
        /// </summary>
        internal static string Prepupa {
            get {
                return ResourceManager.GetString("Prepupa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRP.
        /// </summary>
        internal static string PrepupaR {
            get {
                return ResourceManager.GetString("PrepupaR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pupa.
        /// </summary>
        internal static string Pupa {
            get {
                return ResourceManager.GetString("Pupa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUP.
        /// </summary>
        internal static string PupaR {
            get {
                return ResourceManager.GetString("PupaR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subimago.
        /// </summary>
        internal static string Subimago {
            get {
                return ResourceManager.GetString("Subimago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIM.
        /// </summary>
        internal static string SubimagoR {
            get {
                return ResourceManager.GetString("SubimagoR", resourceCulture);
            }
        }
    }
}
