//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mayfly.Fish.Resources.Interface {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mayfly.Fish.Resources.Interface.EU", typeof(EU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal efforts, std units.
        /// </summary>
        public static string NominalEfforts {
            get {
                return ResourceManager.GetString("NominalEfforts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation time, days.
        /// </summary>
        public static string NominalSpan {
            get {
                return ResourceManager.GetString("NominalSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal square, ha × 24h.
        /// </summary>
        public static string NominalSquare {
            get {
                return ResourceManager.GetString("NominalSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal volume, ths. m³ × 24h.
        /// </summary>
        public static string NominalVolume {
            get {
                return ResourceManager.GetString("NominalVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square, ha.
        /// </summary>
        public static string RealSquare {
            get {
                return ResourceManager.GetString("RealSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume, ths. m³.
        /// </summary>
        public static string RealVolume {
            get {
                return ResourceManager.GetString("RealVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to std units.
        /// </summary>
        public static string UnitEfforts {
            get {
                return ResourceManager.GetString("UnitEfforts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ha.
        /// </summary>
        public static string UnitSquare {
            get {
                return ResourceManager.GetString("UnitSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ths. m³.
        /// </summary>
        public static string UnitVolume {
            get {
                return ResourceManager.GetString("UnitVolume", resourceCulture);
            }
        }
    }
}
