//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mayfly.Mathematics.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Chaddock {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Chaddock() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mayfly.Mathematics.Resources.Chaddock", typeof(Chaddock).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is absent.
        /// </summary>
        public static string Strength0 {
            get {
                return ResourceManager.GetString("Strength0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is weak.
        /// </summary>
        public static string Strength1 {
            get {
                return ResourceManager.GetString("Strength1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is moderate.
        /// </summary>
        public static string Strength2 {
            get {
                return ResourceManager.GetString("Strength2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is salient.
        /// </summary>
        public static string Strength3 {
            get {
                return ResourceManager.GetString("Strength3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is high.
        /// </summary>
        public static string Strength4 {
            get {
                return ResourceManager.GetString("Strength4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection is very high.
        /// </summary>
        public static string Strength5 {
            get {
                return ResourceManager.GetString("Strength5", resourceCulture);
            }
        }
    }
}
