//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mayfly.Plankton.Explorer.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Interface {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Interface() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mayfly.Plankton.Explorer.Resources.Interface", typeof(Interface).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cards.
        /// </summary>
        internal static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cards Analysis Closing.
        /// </summary>
        internal static string CardsClosing {
            get {
                return ResourceManager.GetString("CardsClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to save log changes?.
        /// </summary>
        internal static string CardsClosingInstruction {
            get {
                return ResourceManager.GetString("CardsClosingInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are some changes of initial data log. Saving it will rewrite cards files with changes have been made..
        /// </summary>
        internal static string CardsClosingText {
            get {
                return ResourceManager.GetString("CardsClosingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} records are selected according to specified terms.
        /// </summary>
        internal static string CasesFilteredText {
            get {
                return ResourceManager.GetString("CasesFilteredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} records was selected.
        /// </summary>
        internal static string CasesFilteredTitle {
            get {
                return ResourceManager.GetString("CasesFilteredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сезонная периодичность.
        /// </summary>
        internal static string DayOfYear {
            get {
                return ResourceManager.GetString("DayOfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total consumption rate, ind./g.
        /// </summary>
        internal static string DietAbundance {
            get {
                return ResourceManager.GetString("DietAbundance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total consumption rate, ‰.
        /// </summary>
        internal static string DietBiomass {
            get {
                return ResourceManager.GetString("DietBiomass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Diet Explorer.
        /// </summary>
        internal static string DietTitle {
            get {
                return ResourceManager.GetString("DietTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Consumption rate, ind./g.
        /// </summary>
        internal static string DietTxAbundance {
            get {
                return ResourceManager.GetString("DietTxAbundance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Consumption rate, ‰.
        /// </summary>
        internal static string DietTxBiomass {
            get {
                return ResourceManager.GetString("DietTxBiomass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Predator mass, g.
        /// </summary>
        internal static string DietVolume {
            get {
                return ResourceManager.GetString("DietVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Benthos Collection Cards Filter.
        /// </summary>
        internal static string FilterCards {
            get {
                return ResourceManager.GetString("FilterCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cases Filter.
        /// </summary>
        internal static string FilterCases {
            get {
                return ResourceManager.GetString("FilterCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Waters Filter.
        /// </summary>
        internal static string FilterWaters {
            get {
                return ResourceManager.GetString("FilterWaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group (log).
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Groupl (log, cumulative).
        /// </summary>
        internal static string GroupsCumul {
            get {
                return ResourceManager.GetString("GroupsCumul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Individuals Log Processing.
        /// </summary>
        internal static string IndividualsProcessing {
            get {
                return ResourceManager.GetString("IndividualsProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Суточная периодичность.
        /// </summary>
        internal static string TimeOfDay {
            get {
                return ResourceManager.GetString("TimeOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Waters.
        /// </summary>
        internal static string Waters {
            get {
                return ResourceManager.GetString("Waters", resourceCulture);
            }
        }
    }
}
