//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mayfly.Fish.Explorer.Resources.Interface {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Process {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Process() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mayfly.Fish.Explorer.Resources.Interface.Process", typeof(Process).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Age parameters export.
        /// </summary>
        internal static string AgeParameters {
            get {
                return ResourceManager.GetString("AgeParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Age distribution export.
        /// </summary>
        internal static string AgeStructure {
            get {
                return ResourceManager.GetString("AgeStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Biological parameters export.
        /// </summary>
        internal static string BioParameters {
            get {
                return ResourceManager.GetString("BioParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Catches calculation.
        /// </summary>
        internal static string CatchesProcessing {
            get {
                return ResourceManager.GetString("CatchesProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculating CPUE.
        /// </summary>
        internal static string CpueProcessing {
            get {
                return ResourceManager.GetString("CpueProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Diet compiling.
        /// </summary>
        internal static string DietCompiling {
            get {
                return ResourceManager.GetString("DietCompiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Effort calculation.
        /// </summary>
        internal static string EffortCalculation {
            get {
                return ResourceManager.GetString("EffortCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Initial data logs export.
        /// </summary>
        internal static string InitialDataLogExport {
            get {
                return ResourceManager.GetString("InitialDataLogExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mass calculation.
        /// </summary>
        internal static string MassCalculation {
            get {
                return ResourceManager.GetString("MassCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Catch parameters export (mesh).
        /// </summary>
        internal static string MeshCatchParameters {
            get {
                return ResourceManager.GetString("MeshCatchParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compiling rating report.
        /// </summary>
        internal static string RateReportProcessing {
            get {
                return ResourceManager.GetString("RateReportProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bio compiling.
        /// </summary>
        internal static string SpecCompiling {
            get {
                return ResourceManager.GetString("SpecCompiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Catch parameters export (species).
        /// </summary>
        internal static string SpeciesCatchParameters {
            get {
                return ResourceManager.GetString("SpeciesCatchParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Species sample estimation.
        /// </summary>
        internal static string SpeciesSample {
            get {
                return ResourceManager.GetString("SpeciesSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Species structure analysis.
        /// </summary>
        internal static string SpeciesStructure {
            get {
                return ResourceManager.GetString("SpeciesStructure", resourceCulture);
            }
        }
    }
}
