//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mayfly.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DateTime {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DateTime() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mayfly.Resources.DateTime", typeof(DateTime).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        public static string DayPeriod0 {
            get {
                return ResourceManager.GetString("DayPeriod0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morning.
        /// </summary>
        public static string DayPeriod1 {
            get {
                return ResourceManager.GetString("DayPeriod1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string DayPeriod2 {
            get {
                return ResourceManager.GetString("DayPeriod2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening.
        /// </summary>
        public static string DayPeriod3 {
            get {
                return ResourceManager.GetString("DayPeriod3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}0-s.
        /// </summary>
        public static string DecadeMask {
            get {
                return ResourceManager.GetString("DecadeMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday at {0:t}.
        /// </summary>
        public static string DescDay {
            get {
                return ResourceManager.GetString("DescDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On {0:m}.
        /// </summary>
        public static string DescMonth {
            get {
                return ResourceManager.GetString("DescMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On last {0:dddd} at {1:t}.
        /// </summary>
        public static string DescWeek {
            get {
                return ResourceManager.GetString("DescWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On {0:m} this year.
        /// </summary>
        public static string DescYear {
            get {
                return ResourceManager.GetString("DescYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winter.
        /// </summary>
        public static string Season0 {
            get {
                return ResourceManager.GetString("Season0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spring.
        /// </summary>
        public static string Season1 {
            get {
                return ResourceManager.GetString("Season1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summer.
        /// </summary>
        public static string Season2 {
            get {
                return ResourceManager.GetString("Season2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autumn.
        /// </summary>
        public static string Season3 {
            get {
                return ResourceManager.GetString("Season3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:yyyy}, Week {1}.
        /// </summary>
        public static string WeekOfYear {
            get {
                return ResourceManager.GetString("WeekOfYear", resourceCulture);
            }
        }
    }
}
