//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mayfly.Software.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Interface {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Interface() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mayfly.Software.Resources.Interface", typeof(Interface).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        internal static string Agree {
            get {
                return ResourceManager.GetString("Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading feature ({0}).
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading feature ({0}) localization files ({1}).
        /// </summary>
        internal static string DownloadingCulture {
            get {
                return ResourceManager.GetString("DownloadingCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing files.
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing feature ({0}).
        /// </summary>
        internal static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering file type: {0}.
        /// </summary>
        internal static string RegFileType {
            get {
                return ResourceManager.GetString("RegFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering property handler: {0}.
        /// </summary>
        internal static string RegPropertyHandler {
            get {
                return ResourceManager.GetString("RegPropertyHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating registry values.
        /// </summary>
        internal static string RegWork {
            get {
                return ResourceManager.GetString("RegWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files and folders removed.
        /// </summary>
        internal static string RemoveFiles {
            get {
                return ResourceManager.GetString("RemoveFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut {0} removed.
        /// </summary>
        internal static string RemoveShortcuts {
            get {
                return ResourceManager.GetString("RemoveShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating shortcuts.
        /// </summary>
        internal static string Shortcuts {
            get {
                return ResourceManager.GetString("Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start goup removed.
        /// </summary>
        internal static string StartGroupRemoved {
            get {
                return ResourceManager.GetString("StartGroupRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File type unregistered: {0}.
        /// </summary>
        internal static string UnregFileType {
            get {
                return ResourceManager.GetString("UnregFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry is cleaned up.
        /// </summary>
        internal static string UnregWork {
            get {
                return ResourceManager.GetString("UnregWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading feature ({0}).
        /// </summary>
        internal static string UpdateDownload {
            get {
                return ResourceManager.GetString("UpdateDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading feature ({0}) localization files ({1}).
        /// </summary>
        internal static string UpdateDownloadLoc {
            get {
                return ResourceManager.GetString("UpdateDownloadLoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is just updated.
        /// </summary>
        internal static string UpdateInstalled {
            get {
                return ResourceManager.GetString("UpdateInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version was downloaded and installed automatically. Click here to see changes in new version..
        /// </summary>
        internal static string UpdateInstalledInstruction {
            get {
                return ResourceManager.GetString("UpdateInstalledInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing feature ({0}).
        /// </summary>
        internal static string UpdateInstalling {
            get {
                return ResourceManager.GetString("UpdateInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some published updates for {0}. 
        ///We are ready to download and install these updates.
        ///Close all Mayfly windows and click &apos;Next&apos; to read release notes..
        /// </summary>
        internal static string UpdatesReady {
            get {
                return ResourceManager.GetString("UpdatesReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string VerbEdit {
            get {
                return ResourceManager.GetString("VerbEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string VerbOpen {
            get {
                return ResourceManager.GetString("VerbOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run analysis.
        /// </summary>
        internal static string VerbRun {
            get {
                return ResourceManager.GetString("VerbRun", resourceCulture);
            }
        }
    }
}
