//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mayfly.Wild.Resources.Interface {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Diversity {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Diversity() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mayfly.Wild.Resources.Interface.Diversity", typeof(Diversity).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simpson, 1949.
        /// </summary>
        public static string D1949_Simpson {
            get {
                return ResourceManager.GetString("D1949_Simpson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margalef, 1958.
        /// </summary>
        public static string D1958_Margalef {
            get {
                return ResourceManager.GetString("D1958_Margalef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shannon &amp; Weaver, 1963.
        /// </summary>
        public static string D1963_Shannon {
            get {
                return ResourceManager.GetString("D1963_Shannon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menhinick, 1964.
        /// </summary>
        public static string D1964_Menhinick {
            get {
                return ResourceManager.GetString("D1964_Menhinick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pielou, 1966.
        /// </summary>
        public static string D1966_Pielou {
            get {
                return ResourceManager.GetString("D1966_Pielou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to McIntosh, 1967.
        /// </summary>
        public static string D1967_McIntosh {
            get {
                return ResourceManager.GetString("D1967_McIntosh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berger &amp; Parker, 1970.
        /// </summary>
        public static string D1970_BergerParker {
            get {
                return ResourceManager.GetString("D1970_BergerParker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to von Foerster, 1974.
        /// </summary>
        public static string D1974_Foerster {
            get {
                return ResourceManager.GetString("D1974_Foerster", resourceCulture);
            }
        }
    }
}
