//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mayfly.Wild.Resources.Interface {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Interface {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Interface() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mayfly.Wild.Resources.Interface.Interface", typeof(Interface).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey of {0}.
        /// </summary>
        public static string AnnualSurveyItem {
            get {
                return ResourceManager.GetString("AnnualSurveyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates: {0}; Places: {1}.
        /// </summary>
        public static string BioFormat {
            get {
                return ResourceManager.GetString("BioFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} categories.
        /// </summary>
        public static string CompositionPresentation {
            get {
                return ResourceManager.GetString("CompositionPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added automatically.
        /// </summary>
        public static string DuplicateDefaultComment {
            get {
                return ResourceManager.GetString("DuplicateDefaultComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Data Folder.
        /// </summary>
        public static string FieldFolder {
            get {
                return ResourceManager.GetString("FieldFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage for field data cards, references etc..
        /// </summary>
        public static string FieldFolderTip {
            get {
                return ResourceManager.GetString("FieldFolderTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting data....
        /// </summary>
        public static string GetData {
            get {
                return ResourceManager.GetString("GetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Individuals Log.
        /// </summary>
        public static string IndLog {
            get {
                return ResourceManager.GetString("IndLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tally.
        /// </summary>
        public static string IndNo {
            get {
                return ResourceManager.GetString("IndNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. Individual profile.
        /// </summary>
        public static string IndWindow {
            get {
                return ResourceManager.GetString("IndWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:s} at {1:s}.
        /// </summary>
        public static string LogMask {
            get {
                return ResourceManager.GetString("LogMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model calculation.
        /// </summary>
        public static string ModelCalc {
            get {
                return ResourceManager.GetString("ModelCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more data.
        /// </summary>
        public static string MoreExtraData {
            get {
                return ResourceManager.GetString("MoreExtraData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data....
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No precipitations.
        /// </summary>
        public static string NoPrecip {
            get {
                return ResourceManager.GetString("NoPrecip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality of method is {0:P1}.
        /// </summary>
        public static string QualityTip {
            get {
                return ResourceManager.GetString("QualityTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality is very low.
        /// </summary>
        public static string QualityTipBad {
            get {
                return ResourceManager.GetString("QualityTipBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previously defined as {0}.
        /// </summary>
        public static string RedefineComment {
            get {
                return ResourceManager.GetString("RedefineComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample collected {0:D} at {1:t} in {2} by {3} with {4}.
        /// </summary>
        public static string SampleFormat {
            get {
                return ResourceManager.GetString("SampleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species: 0.
        /// </summary>
        public static string SpeciesCount {
            get {
                return ResourceManager.GetString("SpeciesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lack of data.
        /// </summary>
        public static string SuggestionUnavailable {
            get {
                return ResourceManager.GetString("SuggestionUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Water.
        /// </summary>
        public static string WaterUnknown {
            get {
                return ResourceManager.GetString("WaterUnknown", resourceCulture);
            }
        }
    }
}
