//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mayfly.Wild.Resources.Interface {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Process {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Process() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mayfly.Wild.Resources.Interface.Process", typeof(Process).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Looking for artefacts.
        /// </summary>
        public static string ArtefactsProcessing {
            get {
                return ResourceManager.GetString("ArtefactsProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cards loading.
        /// </summary>
        public static string CardsLoading {
            get {
                return ResourceManager.GetString("CardsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cards log loading.
        /// </summary>
        public static string CardsProcessing {
            get {
                return ResourceManager.GetString("CardsProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cards saving.
        /// </summary>
        public static string CardsSaving {
            get {
                return ResourceManager.GetString("CardsSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Individuals data extension.
        /// </summary>
        public static string ExtInd {
            get {
                return ResourceManager.GetString("ExtInd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Species log extension.
        /// </summary>
        public static string ExtSpc {
            get {
                return ResourceManager.GetString("ExtSpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stratified samples extension.
        /// </summary>
        public static string ExtStrat {
            get {
                return ResourceManager.GetString("ExtStrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Individuals log processing.
        /// </summary>
        public static string IndividualsProcessing {
            get {
                return ResourceManager.GetString("IndividualsProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Estimating data rate.
        /// </summary>
        public static string RateProcessing {
            get {
                return ResourceManager.GetString("RateProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filtering.
        /// </summary>
        public static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reading investigators&apos; signs.
        /// </summary>
        public static string SignProcessing {
            get {
                return ResourceManager.GetString("SignProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculating similarity indices.
        /// </summary>
        public static string SimCalc {
            get {
                return ResourceManager.GetString("SimCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Applying bio.
        /// </summary>
        public static string SpecApply {
            get {
                return ResourceManager.GetString("SpecApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Species log processing.
        /// </summary>
        public static string SpeciesProcessing {
            get {
                return ResourceManager.GetString("SpeciesProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading bio.
        /// </summary>
        public static string SpecLoading {
            get {
                return ResourceManager.GetString("SpecLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stratified samples loading.
        /// </summary>
        public static string StratifiedProcessing {
            get {
                return ResourceManager.GetString("StratifiedProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total report compilation.
        /// </summary>
        public static string TotalReportProcessing {
            get {
                return ResourceManager.GetString("TotalReportProcessing", resourceCulture);
            }
        }
    }
}
