//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mayfly.Wild.Resources.Interface {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Process {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Process() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mayfly.Wild.Resources.Interface.Process", typeof(Process).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for artifacts.
        /// </summary>
        public static string ArtifactsProcessing {
            get {
                return ResourceManager.GetString("ArtifactsProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards loading.
        /// </summary>
        public static string CardsLoading {
            get {
                return ResourceManager.GetString("CardsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards log loading.
        /// </summary>
        public static string CardsProcessing {
            get {
                return ResourceManager.GetString("CardsProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards saving.
        /// </summary>
        public static string CardsSaving {
            get {
                return ResourceManager.GetString("CardsSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individuals data extension.
        /// </summary>
        public static string ExtInd {
            get {
                return ResourceManager.GetString("ExtInd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species log extension.
        /// </summary>
        public static string ExtSpc {
            get {
                return ResourceManager.GetString("ExtSpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stratified samples extension.
        /// </summary>
        public static string ExtStrat {
            get {
                return ResourceManager.GetString("ExtStrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individuals log processing.
        /// </summary>
        public static string IndividualsProcessing {
            get {
                return ResourceManager.GetString("IndividualsProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimating data rate.
        /// </summary>
        public static string RateProcessing {
            get {
                return ResourceManager.GetString("RateProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering.
        /// </summary>
        public static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading investigators&apos; signs.
        /// </summary>
        public static string SignProcessing {
            get {
                return ResourceManager.GetString("SignProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating similarity indices.
        /// </summary>
        public static string SimCalc {
            get {
                return ResourceManager.GetString("SimCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying bio.
        /// </summary>
        public static string SpecApply {
            get {
                return ResourceManager.GetString("SpecApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species log processing.
        /// </summary>
        public static string SpeciesProcessing {
            get {
                return ResourceManager.GetString("SpeciesProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading bio.
        /// </summary>
        public static string SpecLoading {
            get {
                return ResourceManager.GetString("SpecLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stratified samples loading.
        /// </summary>
        public static string StratifiedProcessing {
            get {
                return ResourceManager.GetString("StratifiedProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total report compilation.
        /// </summary>
        public static string TotalReportProcessing {
            get {
                return ResourceManager.GetString("TotalReportProcessing", resourceCulture);
            }
        }
    }
}
