//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mayfly.Fish.Explorer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Artefact {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Artefact() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mayfly.Fish.Explorer.Resources.Artefact", typeof(Artefact).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some artefacts found in data..
        /// </summary>
        internal static string ArtefactsFound {
            get {
                return ResourceManager.GetString("ArtefactsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card have not enough information to calculate fishing effort.
        /// </summary>
        internal static string CardEffort {
            get {
                return ResourceManager.GetString("CardEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} individuals have some issues with tally.
        /// </summary>
        internal static string IndividualsTally {
            get {
                return ResourceManager.GetString("IndividualsTally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} diet samples have unweighted individuals in diet sample.
        /// </summary>
        internal static string IndividualsUnweightedDiet {
            get {
                return ResourceManager.GetString("IndividualsUnweightedDiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample, e. g. age, fecundity, diet or parasitological issues, was not marked with tally.
        /// </summary>
        internal static string IndividualTallyMissing {
            get {
                return ResourceManager.GetString("IndividualTallyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Had tally ({0}) but doesn&apos;t contain any registered information, e. g. age, fecundity, diet or parasitological issues.
        /// </summary>
        internal static string IndividualTallyOdd {
            get {
                return ResourceManager.GetString("IndividualTallyOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has {0} unweighted individuals in diet sample.
        /// </summary>
        internal static string IndividualUnweightedDiet {
            get {
                return ResourceManager.GetString("IndividualUnweightedDiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} specimen with length not measured.
        /// </summary>
        internal static string LogLength {
            get {
                return ResourceManager.GetString("LogLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} log records with unmeasured specimen.
        /// </summary>
        internal static string LogLengths {
            get {
                return ResourceManager.GetString("LogLengths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record mass ({0:n3} kg) is more than detailed mass, e. g. mass of individuals and calculated mass of stratified sample ({1:n3}) which is fine.
        /// </summary>
        internal static string LogMassMissing {
            get {
                return ResourceManager.GetString("LogMassMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record mass ({0:n3} kg) is {1:p1} less than detailed mass, e. g. mass of individuals and calculated mass of stratified sample ({2:n3}).
        /// </summary>
        internal static string LogMassOdd {
            get {
                return ResourceManager.GetString("LogMassOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} log records mass not equal detailed mass, e. g. mass of individuals and calculated mass of stratified sample.
        /// </summary>
        internal static string LogMassOdds {
            get {
                return ResourceManager.GetString("LogMassOdds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total quantity of {0} specified as {1}
        ///but in individuals log there are {2} specimen and
        ///in stratified samples there are {3} specimen, so {4} are missing.
        /// </summary>
        internal static string Specimen {
            get {
                return ResourceManager.GetString("Specimen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity of specimens can&apos;t be calculated 
        ///because in some cards it is not specified.
        /// </summary>
        internal static string SpecimenUnable {
            get {
                return ResourceManager.GetString("SpecimenUnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} measures have {1} outliers.
        /// </summary>
        internal static string ValueHasOutliers {
            get {
                return ResourceManager.GetString("ValueHasOutliers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} specimen is not measured.
        ///It can&apos;t be calculated any way because of 
        ///lack of studied specimens.
        /// </summary>
        internal static string ValueIsCritical {
            get {
                return ResourceManager.GetString("ValueIsCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} specimen is not measured. 
        ///However, it can be obtained from length.
        /// </summary>
        internal static string ValueIsRecoverable {
            get {
                return ResourceManager.GetString("ValueIsRecoverable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} specimen is not measured.
        ///However, it can be obtained from length (but regression contains {2} outliers).
        /// </summary>
        internal static string ValueIsRecoverableButHasOutliers {
            get {
                return ResourceManager.GetString("ValueIsRecoverableButHasOutliers", resourceCulture);
            }
        }
    }
}
