//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mayfly.Fish.Explorer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Interface {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Interface() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mayfly.Fish.Explorer.Resources.Interface", typeof(Interface).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtained by key.
        /// </summary>
        internal static string AgeAdd {
            get {
                return ResourceManager.GetString("AgeAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total quantity, ind..
        /// </summary>
        internal static string AgeGeneral {
            get {
                return ResourceManager.GetString("AgeGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show {0} length/age key.
        /// </summary>
        internal static string AgeRecMenu {
            get {
                return ResourceManager.GetString("AgeRecMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length-to-age key. {0}. {1}.
        /// </summary>
        internal static string AgeRecovery {
            get {
                return ResourceManager.GetString("AgeRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age readings.
        /// </summary>
        internal static string AgeSampled {
            get {
                return ResourceManager.GetString("AgeSampled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No classes.
        /// </summary>
        internal static string AllDataCombined {
            get {
                return ResourceManager.GetString("AllDataCombined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean mass, g.
        /// </summary>
        internal static string AvgMass {
            get {
                return ResourceManager.GetString("AvgMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BPUE, %.
        /// </summary>
        internal static string AxisBPUE {
            get {
                return ResourceManager.GetString("AxisBPUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NPUE, %.
        /// </summary>
        internal static string AxisNPUE {
            get {
                return ResourceManager.GetString("AxisNPUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined data.
        /// </summary>
        internal static string BioCombined {
            get {
                return ResourceManager.GetString("BioCombined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded data.
        /// </summary>
        internal static string BioLoaded {
            get {
                return ResourceManager.GetString("BioLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio.
        /// </summary>
        internal static string BioReference {
            get {
                return ResourceManager.GetString("BioReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fully exploited age groups.
        /// </summary>
        internal static string CatchCurve {
            get {
                return ResourceManager.GetString("CatchCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexploited age groups.
        /// </summary>
        internal static string CatchCurveUnused {
            get {
                return ResourceManager.GetString("CatchCurveUnused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caught in {0} at {1:f}.
        /// </summary>
        internal static string CatchDescription {
            get {
                return ResourceManager.GetString("CatchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catches.
        /// </summary>
        internal static string Catches {
            get {
                return ResourceManager.GetString("Catches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted catches.
        /// </summary>
        internal static string CatchesAdjusted {
            get {
                return ResourceManager.GetString("CatchesAdjusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generation of {0}.
        /// </summary>
        internal static string CohortPresentation {
            get {
                return ResourceManager.GetString("CohortPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} compositions of {2} categories.
        /// </summary>
        internal static string CompositionEqPresentation {
            get {
                return ResourceManager.GetString("CompositionEqPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sufficient.
        /// </summary>
        internal static string EnoughStamp {
            get {
                return ResourceManager.GetString("EnoughStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fleet {0}.
        /// </summary>
        internal static string FleetMask {
            get {
                return ResourceManager.GetString("FleetMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass growth model of {0}.
        /// </summary>
        internal static string MassGrowth {
            get {
                return ResourceManager.GetString("MassGrowth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data from bio.
        /// </summary>
        internal static string QualBio {
            get {
                return ResourceManager.GetString("QualBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined data.
        /// </summary>
        internal static string QualCombi {
            get {
                return ResourceManager.GetString("QualCombi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Own data.
        /// </summary>
        internal static string QualOwn {
            get {
                return ResourceManager.GetString("QualOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultant ogive.
        /// </summary>
        internal static string SelectivityOgive {
            get {
                return ResourceManager.GetString("SelectivityOgive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added from stratified sample.
        /// </summary>
        internal static string SimulatedIndividual {
            get {
                return ResourceManager.GetString("SimulatedIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio export failed.
        /// </summary>
        internal static string SpecFailed {
            get {
                return ResourceManager.GetString("SpecFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is absent in catches of {1}.
        ///To eliminate it from further analysis hold {2}.
        /// </summary>
        internal static string SpeciesOfInterestIsAbsent {
            get {
                return ResourceManager.GetString("SpeciesOfInterestIsAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal length class is {0} cm and maximal is {1} cm..
        /// </summary>
        internal static string StartifiedExtr {
            get {
                return ResourceManager.GetString("StartifiedExtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aged.
        /// </summary>
        internal static string StratesAged {
            get {
                return ResourceManager.GetString("StratesAged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded with bio.
        /// </summary>
        internal static string StratesBio {
            get {
                return ResourceManager.GetString("StratesBio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered.
        /// </summary>
        internal static string StratesRegistered {
            get {
                return ResourceManager.GetString("StratesRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampled.
        /// </summary>
        internal static string StratesSampled {
            get {
                return ResourceManager.GetString("StratesSampled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weighted.
        /// </summary>
        internal static string StratesWeighted {
            get {
                return ResourceManager.GetString("StratesWeighted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stratified samples:
        ///.
        /// </summary>
        internal static string StratifiedPrae {
            get {
                return ResourceManager.GetString("StratifiedPrae", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,7} inds. in {1} in {2} caught with {3}..
        /// </summary>
        internal static string StratifiedShort {
            get {
                return ResourceManager.GetString("StratifiedShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total sample counts {0} ind..
        /// </summary>
        internal static string StratifiedTotal {
            get {
                return ResourceManager.GetString("StratifiedTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observed at {0:f}.
        /// </summary>
        internal static string TimepointDescription {
            get {
                return ResourceManager.GetString("TimepointDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total mass, kg.
        /// </summary>
        internal static string TotalMass {
            get {
                return ResourceManager.GetString("TotalMass", resourceCulture);
            }
        }
    }
}
