//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mayfly.Fish.Explorer.Resources.Reports.Sections {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Selectivity {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Selectivity() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mayfly.Fish.Explorer.Resources.Reports.Sections.Selectivity", typeof(Selectivity).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesh size.
        /// </summary>
        internal static string Column1_1 {
            get {
                return ResourceManager.GetString("Column1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectivity parameters.
        /// </summary>
        internal static string Column1_2 {
            get {
                return ResourceManager.GetString("Column1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size class midpoint, mm.
        /// </summary>
        internal static string Column2_1 {
            get {
                return ResourceManager.GetString("Column2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resultant ogive.
        /// </summary>
        internal static string Column2_2 {
            get {
                return ResourceManager.GetString("Column2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimum length, mm.
        /// </summary>
        internal static string Column2_3 {
            get {
                return ResourceManager.GetString("Column2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectivity estimation is based on {0} catches of gillnets of different mesh sizes. Such data is herefore used and is presented in table {1}..
        /// </summary>
        internal static string Paragraph1 {
            get {
                return ResourceManager.GetString("Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catches of different mesh sizes averaged to obtain mean effort-weighted length composition. It is given in table {0}..
        /// </summary>
        internal static string Paragraph2 {
            get {
                return ResourceManager.GetString("Paragraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimum lengths and selectivity parameters (selection factor and standard deviation) were assessed from length frequency distribution (table {0}) for each mesh size combination (table {1})..
        /// </summary>
        internal static string Paragraph3 {
            get {
                return ResourceManager.GetString("Paragraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values from table {0} were used to estimate the common selectivity factor, the common standard deviation and optimum selection length per mesh size. The common selection factor are {1:N4} and common standard deviation is {2:N4}. Selection values for each length class and length optimum in each mesh size are given in table {3}..
        /// </summary>
        internal static string Paragraph4 {
            get {
                return ResourceManager.GetString("Paragraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Averaged length composition is now adjusted by resultant selection ogive. Results are given in table {0}..
        /// </summary>
        internal static string Paragraph5 {
            get {
                return ResourceManager.GetString("Paragraph5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catches per unit of effort of {0} of different gear classes.
        /// </summary>
        internal static string Table1 {
            get {
                return ResourceManager.GetString("Table1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Averaged length composition of {0} catches.
        /// </summary>
        internal static string Table2 {
            get {
                return ResourceManager.GetString("Table2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} selectivity parameters of {1} with different mesh sizes.
        /// </summary>
        internal static string Table3 {
            get {
                return ResourceManager.GetString("Table3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} selectivity values of different gear classes.
        /// </summary>
        internal static string Table4 {
            get {
                return ResourceManager.GetString("Table4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection adjusted length composition of {0} catches.
        /// </summary>
        internal static string Table5 {
            get {
                return ResourceManager.GetString("Table5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimation of {0} selectivity of {1}.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
