//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mayfly.Fish.Explorer.Resources.Reports.Sections {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VPA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VPA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mayfly.Fish.Explorer.Resources.Reports.Sections.VPA", typeof(VPA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Column1 {
            get {
                return ResourceManager.GetString("Column1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Column2 {
            get {
                return ResourceManager.GetString("Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number caught, ind..
        /// </summary>
        internal static string Column3 {
            get {
                return ResourceManager.GetString("Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fishing mortality.
        /// </summary>
        internal static string Column4 {
            get {
                return ResourceManager.GetString("Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of survivors, ind..
        /// </summary>
        internal static string Column5 {
            get {
                return ResourceManager.GetString("Column5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historic data.
        /// </summary>
        internal static string Header1 {
            get {
                return ResourceManager.GetString("Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortality estimates.
        /// </summary>
        internal static string Header2 {
            get {
                return ResourceManager.GetString("Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual population analisys results.
        /// </summary>
        internal static string Header3 {
            get {
                return ResourceManager.GetString("Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminal value of F assumed {0}..
        /// </summary>
        internal static string NoticeF {
            get {
                return ResourceManager.GetString("NoticeF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source data for virtual population analysis are catches of {0} in consequental years and its age composition. These values are given in table {1}..
        /// </summary>
        internal static string Paragraph1 {
            get {
                return ResourceManager.GetString("Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch history of {0} of different ages are given in table {1}. These values are numbers form table {2} rearranged by age group..
        /// </summary>
        internal static string Paragraph2 {
            get {
                return ResourceManager.GetString("Paragraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural mortality M for VPA assumed {0}. Virtual population analysis for {1}, e. g. estimates of fishing mortalities and numbers of survivors, are given in table {2}..
        /// </summary>
        internal static string Paragraph3 {
            get {
                return ResourceManager.GetString("Paragraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results of VPA rearranged by surveying years are given in table {0}..
        /// </summary>
        internal static string Paragraph4 {
            get {
                return ResourceManager.GetString("Paragraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass of {0} based on VPA results are given in table {1}..
        /// </summary>
        internal static string Paragraph5 {
            get {
                return ResourceManager.GetString("Paragraph5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age compositions of {0} catches in {1}-{2}.
        /// </summary>
        internal static string Table1 {
            get {
                return ResourceManager.GetString("Table1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch history of {0}.
        /// </summary>
        internal static string Table2 {
            get {
                return ResourceManager.GetString("Table2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results of VPA for the {0} {1} cohort.
        /// </summary>
        internal static string Table3 {
            get {
                return ResourceManager.GetString("Table3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population number of {0} in all ages estimated by VPA.
        /// </summary>
        internal static string Table4 {
            get {
                return ResourceManager.GetString("Table4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass of {0} in all ages estimated by VPA, kg.
        /// </summary>
        internal static string Table5 {
            get {
                return ResourceManager.GetString("Table5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual {0} population analysis.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual population analysis routines.
        /// </summary>
        internal static string TitleAppendices {
            get {
                return ResourceManager.GetString("TitleAppendices", resourceCulture);
            }
        }
    }
}
