//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mayfly.Fish.Explorer.Resources.Reports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Caption {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Caption() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mayfly.Fish.Explorer.Resources.Reports.Caption", typeof(Caption).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch.
        /// </summary>
        internal static string Catch {
            get {
                return ResourceManager.GetString("Catch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catchability.
        /// </summary>
        internal static string Catchability {
            get {
                return ResourceManager.GetString("Catchability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPUE.
        /// </summary>
        internal static string CpueAccr {
            get {
                return ResourceManager.GetString("CpueAccr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efforts, {0}.
        /// </summary>
        internal static string Efforts {
            get {
                return ResourceManager.GetString("Efforts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraction of total applied effort, %.
        /// </summary>
        internal static string Fraction {
            get {
                return ResourceManager.GetString("Fraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear class.
        /// </summary>
        internal static string GearClass {
            get {
                return ResourceManager.GetString("GearClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        internal static string Ops {
            get {
                return ResourceManager.GetString("Ops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex ratio.
        /// </summary>
        internal static string SexRatio {
            get {
                return ResourceManager.GetString("SexRatio", resourceCulture);
            }
        }
    }
}
