//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mayfly.Fish.Explorer.Resources.Reports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CatchComposition {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CatchComposition() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mayfly.Fish.Explorer.Resources.Reports.CatchComposition", typeof(CatchComposition).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantities of {0} categories in {1} catches of different gear class, ind..
        /// </summary>
        internal static string App1 {
            get {
                return ResourceManager.GetString("App1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masses of {0} categories in {1} catches of different gear class, kg.
        /// </summary>
        internal static string App2 {
            get {
                return ResourceManager.GetString("App2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPUE (by number) of {0} categories in {1} catches of different gear class, ind./{2}.
        /// </summary>
        internal static string App3 {
            get {
                return ResourceManager.GetString("App3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPUE (by mass) of {0} categories in {1} catches of different gear class, kg/{2}.
        /// </summary>
        internal static string App4 {
            get {
                return ResourceManager.GetString("App4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appendices. Source data for calculation averaged {0} composition of {1} catches..
        /// </summary>
        internal static string AppendixHeader1 {
            get {
                return ResourceManager.GetString("AppendixHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appendices. Age-length keys for calculation of age compositions of {0} catches.
        /// </summary>
        internal static string AppendixHeader2 {
            get {
                return ResourceManager.GetString("AppendixHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * – CPUE displays {0} category presence in a harvest of 1 {1}..
        /// </summary>
        internal static string Notice1 {
            get {
                return ResourceManager.GetString("Notice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * – Age category quantity recovered by length-age key..
        /// </summary>
        internal static string Notice2 {
            get {
                return ResourceManager.GetString("Notice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * – composition was distributed on whole sample..
        /// </summary>
        internal static string Notice3 {
            get {
                return ResourceManager.GetString("Notice3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catches of {0} categories (expressed in number and mass) per unit of efforts (CPUE) and {0} composition of {1} catch are presented in table {2}. Also fractions of juveniles and both genders for each {0} category are given..
        /// </summary>
        internal static string Paragraph1 {
            get {
                return ResourceManager.GetString("Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age composition of {0} was obtained using growth model:.
        /// </summary>
        internal static string Paragraph2 {
            get {
                return ResourceManager.GetString("Paragraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Described model is based on data provided by {0} ({1})..
        /// </summary>
        internal static string Paragraph3 {
            get {
                return ResourceManager.GetString("Paragraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catches {0} composition.
        /// </summary>
        internal static string Table1 {
            get {
                return ResourceManager.GetString("Table1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population {0} composition.
        /// </summary>
        internal static string TablePopulation {
            get {
                return ResourceManager.GetString("TablePopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study of {0} composition of {1} population.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to age.
        /// </summary>
        internal static string TypeAge {
            get {
                return ResourceManager.GetString("TypeAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to length.
        /// </summary>
        internal static string TypeLength {
            get {
                return ResourceManager.GetString("TypeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to special.
        /// </summary>
        internal static string TypeSpecies {
            get {
                return ResourceManager.GetString("TypeSpecies", resourceCulture);
            }
        }
    }
}
