//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mayfly.Fish.Explorer.Resources.Reports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CatchComposition {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CatchComposition() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mayfly.Fish.Explorer.Resources.Reports.CatchComposition", typeof(CatchComposition).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source data for calculation averaged {0} composition of {1} catches.
        /// </summary>
        internal static string AppendixHeader1 {
            get {
                return ResourceManager.GetString("AppendixHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age-length keys for calculation of age compositions of {0} catches.
        /// </summary>
        internal static string AppendixHeader2 {
            get {
                return ResourceManager.GetString("AppendixHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to age category quantity recovered by length-age key.
        /// </summary>
        internal static string Notice2 {
            get {
                return ResourceManager.GetString("Notice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to composition was distributed on whole sample.
        /// </summary>
        internal static string Notice3 {
            get {
                return ResourceManager.GetString("Notice3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPUE of {0} in catches of different gear class.
        /// </summary>
        internal static string TableCPUE {
            get {
                return ResourceManager.GetString("TableCPUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} composition in catches of different gear class.
        /// </summary>
        internal static string TableFraction {
            get {
                return ResourceManager.GetString("TableFraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of {0} categories in {1} catches.
        /// </summary>
        internal static string TableHeaderTail {
            get {
                return ResourceManager.GetString("TableHeaderTail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Population {0} composition.
        /// </summary>
        internal static string TablePopulation {
            get {
                return ResourceManager.GetString("TablePopulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantities and masses of {0} in catches of different gear class.
        /// </summary>
        internal static string TableSampleSize {
            get {
                return ResourceManager.GetString("TableSampleSize", resourceCulture);
            }
        }
    }
}
