//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mayfly.Fish.Explorer.Resources.Reports {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VPA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VPA() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mayfly.Fish.Explorer.Resources.Reports.VPA", typeof(VPA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Year.
        /// </summary>
        internal static string Column2 {
            get {
                return ResourceManager.GetString("Column2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number caught, ind..
        /// </summary>
        internal static string Column3 {
            get {
                return ResourceManager.GetString("Column3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fishing mortality.
        /// </summary>
        internal static string Column4 {
            get {
                return ResourceManager.GetString("Column4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of survivors, ind..
        /// </summary>
        internal static string Column5 {
            get {
                return ResourceManager.GetString("Column5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Historic data.
        /// </summary>
        internal static string Header1 {
            get {
                return ResourceManager.GetString("Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mortality estimates.
        /// </summary>
        internal static string Header2 {
            get {
                return ResourceManager.GetString("Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Virtual population analisys results.
        /// </summary>
        internal static string Header3 {
            get {
                return ResourceManager.GetString("Header3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Terminal value of F assumed {0}..
        /// </summary>
        internal static string NoticeF {
            get {
                return ResourceManager.GetString("NoticeF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Source data for virtual population analysis are catches of {0} in consequental years and its age composition. These values are given in table {1}..
        /// </summary>
        internal static string Paragraph1 {
            get {
                return ResourceManager.GetString("Paragraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Catch history of {0} of different ages are given in table {1}. These values are numbers form table {2} rearranged by age group..
        /// </summary>
        internal static string Paragraph2 {
            get {
                return ResourceManager.GetString("Paragraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Natural mortality M for VPA assumed {0}. Virtual population analysis for {1}, e. g. estimates of fishing mortalities and numbers of survivors, are given in table {2}..
        /// </summary>
        internal static string Paragraph3 {
            get {
                return ResourceManager.GetString("Paragraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Results of VPA rearranged by surveying years are given in table {0}..
        /// </summary>
        internal static string Paragraph4 {
            get {
                return ResourceManager.GetString("Paragraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mass of {0} based on VPA results are given in table {1}..
        /// </summary>
        internal static string Paragraph5 {
            get {
                return ResourceManager.GetString("Paragraph5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Age compositions of {0} catches in {1}-{2}.
        /// </summary>
        internal static string Table1 {
            get {
                return ResourceManager.GetString("Table1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Catch history of {0}.
        /// </summary>
        internal static string Table2 {
            get {
                return ResourceManager.GetString("Table2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Results of VPA for the {0} {1} cohort.
        /// </summary>
        internal static string Table3 {
            get {
                return ResourceManager.GetString("Table3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Population number of {0} in all ages estimated by VPA.
        /// </summary>
        internal static string Table4 {
            get {
                return ResourceManager.GetString("Table4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mass of {0} in all ages estimated by VPA, kg.
        /// </summary>
        internal static string Table5 {
            get {
                return ResourceManager.GetString("Table5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Virtual {0} population analysis.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Virtual population analysis routines.
        /// </summary>
        internal static string TitleAppendices {
            get {
                return ResourceManager.GetString("TitleAppendices", resourceCulture);
            }
        }
    }
}
