//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mayfly.Species.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Interface {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Interface() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mayfly.Species.Resources.Interface", typeof(Interface).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click middle mouse button
        ///to see more pictures.
        /// </summary>
        public static string ChangePictureTip {
            get {
                return ResourceManager.GetString("ChangePictureTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is empty.
        /// </summary>
        public static string DescriptionNull {
            get {
                return ResourceManager.GetString("DescriptionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license does not allow to create new species index files..
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown species of genus {0}.
        /// </summary>
        public static string GenusToolTip {
            get {
                return ResourceManager.GetString("GenusToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to.
        /// </summary>
        public static string Goto {
            get {
                return ResourceManager.GetString("Goto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification Keys.
        /// </summary>
        public static string KeyCaption {
            get {
                return ResourceManager.GetString("KeyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depart from {0:f}.
        /// </summary>
        public static string MenuDepart {
            get {
                return ResourceManager.GetString("MenuDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New base.
        /// </summary>
        public static string NewBase {
            get {
                return ResourceManager.GetString("NewBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New species.
        /// </summary>
        public static string NewSpecies {
            get {
                return ResourceManager.GetString("NewSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0}.
        /// </summary>
        public static string NewTaxon {
            get {
                return ResourceManager.GetString("NewTaxon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:l} is now synonimized with {1:l}.
        /// </summary>
        public static string ResultSpcToSpcSynonymized {
            get {
                return ResourceManager.GetString("ResultSpcToSpcSynonymized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:l} is included in {1:f}.
        /// </summary>
        public static string ResultSpcToTaxIncluded {
            get {
                return ResourceManager.GetString("ResultSpcToTaxIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:f} is now derived from {1:f}.
        /// </summary>
        public static string ResultTaxToTaxDerived {
            get {
                return ResourceManager.GetString("ResultTaxToTaxDerived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:f} is now phylogenetically higher than {1:f}.
        /// </summary>
        public static string ResultTaxToTaxSorted {
            get {
                return ResourceManager.GetString("ResultTaxToTaxSorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species: {0}
        ///Taxon: {1}.
        /// </summary>
        public static string SpeciesItemTip {
            get {
                return ResourceManager.GetString("SpeciesItemTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species List.
        /// </summary>
        public static string SpeciesListCaption {
            get {
                return ResourceManager.GetString("SpeciesListCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species record for {0} is missing.
        /// </summary>
        public static string SpeciesNotFound {
            get {
                return ResourceManager.GetString("SpeciesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is loaded.
        /// </summary>
        public static string StatusLoaded {
            get {
                return ResourceManager.GetString("StatusLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List loading.
        /// </summary>
        public static string StatusLoadingList {
            get {
                return ResourceManager.GetString("StatusLoadingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree loading.
        /// </summary>
        public static string StatusLoadingTree {
            get {
                return ResourceManager.GetString("StatusLoadingTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is saved.
        /// </summary>
        public static string StatusSaved {
            get {
                return ResourceManager.GetString("StatusSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select {0}.
        /// </summary>
        public static string TaxonSelect {
            get {
                return ResourceManager.GetString("TaxonSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thesis {0}.
        /// </summary>
        public static string Thesis {
            get {
                return ResourceManager.GetString("Thesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} species.
        /// </summary>
        public static string TipSpcMultiple {
            get {
                return ResourceManager.GetString("TipSpcMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set {0:l} as minor synonim(-s) of {1:l}.
        /// </summary>
        public static string TipSpcToSpcSynonym {
            get {
                return ResourceManager.GetString("TipSpcToSpcSynonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to synonimize species to itself.
        /// </summary>
        public static string TipSpcToSpcSynonymUnableItself {
            get {
                return ResourceManager.GetString("TipSpcToSpcSynonymUnableItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to synonimize species from different taxonomic branches.
        /// </summary>
        public static string TipSpcToSpcSynonymUnableSeparateBranch {
            get {
                return ResourceManager.GetString("TipSpcToSpcSynonymUnableSeparateBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include {0:l} in {1:f}.
        /// </summary>
        public static string TipSpcToTaxInclude {
            get {
                return ResourceManager.GetString("TipSpcToTaxInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derive {0:f} from {1:f}.
        /// </summary>
        public static string TipTaxToTaxDerive {
            get {
                return ResourceManager.GetString("TipTaxToTaxDerive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:f} is already derived from {1:f}.
        /// </summary>
        public static string TipTaxToTaxDeriveUnableAlready {
            get {
                return ResourceManager.GetString("TipTaxToTaxDeriveUnableAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:f} has higher or same rank as {1:f}.
        /// </summary>
        public static string TipTaxToTaxDeriveUnableWrongRank {
            get {
                return ResourceManager.GetString("TipTaxToTaxDeriveUnableWrongRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set {0:f} higher position over {1:f}.
        /// </summary>
        public static string TipTaxToTaxSort {
            get {
                return ResourceManager.GetString("TipTaxToTaxSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Not identified&gt;.
        /// </summary>
        public static string UnidentifiedTitle {
            get {
                return ResourceManager.GetString("UnidentifiedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Varia {
            get {
                return ResourceManager.GetString("Varia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others ({0}).
        /// </summary>
        public static string VariaCount {
            get {
                return ResourceManager.GetString("VariaCount", resourceCulture);
            }
        }
    }
}
