//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mayfly.Species.Systematics.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mayfly.Species.Systematics.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are going to associate {0} with {1}.
        /// </summary>
        public static string AssociateTip {
            get {
                return ResourceManager.GetString("AssociateTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default species key is not specified yet. Set the species key you want to use. You can change it in &apos;Settings&apos; later..
        /// </summary>
        public static string DefaultNotSet {
            get {
                return ResourceManager.GetString("DefaultNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default species key not set.
        /// </summary>
        public static string DefaultNotSetTitle {
            get {
                return ResourceManager.GetString("DefaultNotSetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to completely delete {0} record or just except it from {1}?.
        /// </summary>
        public static string DeleteSpeciesContent {
            get {
                return ResourceManager.GetString("DeleteSpeciesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0 species found.
        /// </summary>
        public static string Filtered {
            get {
                return ResourceManager.GetString("Filtered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are going to reassociate {0} from {1} to {2}.
        /// </summary>
        public static string ReassociateTip {
            get {
                return ResourceManager.GetString("ReassociateTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reference saved.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Associating current thesis with {0} you will delete all subsequent keys. Continue anyway?.
        /// </summary>
        public static string SpeciesAssociateContent {
            get {
                return ResourceManager.GetString("SpeciesAssociateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} associated with {1}.
        /// </summary>
        public static string SpeciesAssociated {
            get {
                return ResourceManager.GetString("SpeciesAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Creation of  new thesis will delete association with {0}. Continue anyway?.
        /// </summary>
        public static string SpeciesDeassociateContent {
            get {
                return ResourceManager.GetString("SpeciesDeassociateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Key is not refering to {0} anymore.
        /// </summary>
        public static string SpeciesDeassociated {
            get {
                return ResourceManager.GetString("SpeciesDeassociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} is already associated with {1}. Would you like to move it  up into {2}?.
        /// </summary>
        public static string SpeciesReassociateContent {
            get {
                return ResourceManager.GetString("SpeciesReassociateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} moved from {1} into {2}.
        /// </summary>
        public static string SpeciesReassociated {
            get {
                return ResourceManager.GetString("SpeciesReassociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current sequance is already associated with {0}. Continue to reassociate it with {1} anyway?.
        /// </summary>
        public static string TaxaReassociateContent {
            get {
                return ResourceManager.GetString("TaxaReassociateContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current sequence reassotiated from {0} to {1}.
        /// </summary>
        public static string TaxaReassociated {
            get {
                return ResourceManager.GetString("TaxaReassociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thesis is not following to any other: &quot;{0}&quot;.
        ///You can edit sequence in edit mode or turn back and try another way..
        /// </summary>
        public static string ThesisIsOpen {
            get {
                return ResourceManager.GetString("ThesisIsOpen", resourceCulture);
            }
        }
    }
}
